package com.carrental.carrental.domain.enums;

public enum BrandEnum {
    ACURA, ALFA_ROMEO, AUDI, BMW, BENTLEY, BUICK, CADILLAC, CHEVROLET,
    CHRYSLER, DODGE, FIAT, FORD, GMC, GENESIS, HONDA, HYUNDAI, INFINITI,
    JAGUAR, JEEP, KIA, LAND_ROVER, LEXUS, LINCOLN, LOTUS, LUCID, MASERATI,
    MAZDA, MERCEDES_BENZ, MERCURY, MINI, MITSUBISHI, NISSAN, POLESTAR,
    PONTIAC, PORSCHE, RAM, RIVIAN, ROLLS_ROYCE, SAAB, SATURN, SCION,
    SMART, SUBARU, SUZUKI, TESLA, TOYOTA, VOLKSWAGEN, VOLVO
}
